### ISSUE TITLE
Release updated rest-client version dependency to RubyGems.org

### ISSUE THREAD

**Issue by rlue** [bennesp/telegramAPI#5]
It looks like the gemspec was updated about a week ago to specify `rest-client >= 2.0.1`, ostensibly for [this fix](https://github.com/rest-client/rest-client/issues/612). However, it appears that this updated gemspec has not been pushed to rubygems.org.

Any chance we could get a version bump to 1.4.2 with this new dependency spec?

**Comment by bennesp** [comment]
Version 1.4.2 of the gem, with new dependency spec, is online
```gem update telegramAPI``` should do the trick
